// vue_test/src/App.vue
<template>
  <div id="app">
    <Menu v-bind="{createRows, addRows, removeRows}" />
    <table class="data-table">
      <tbody>
        <Row v-for="item in data"
        :rowId="item.id"
        :rowLabel="item.label"
        class="data-row" />
      </tbody>
    </table>
  </div>
</template>

<script>
import Menu from './components/Menu.vue'
import Row from './components/Row.vue'
import buildData from './dummyData'


export default {
  name: 'app',
  data() {
    return {
      numberOfRows: 0,
      data: [],
    }
  },
  components: {
    Menu,
    Row
  },
  methods: {

    addRows( amount) {
      this.numberOfRows = this.numberOfRows + amount;
      let data = this.data;
      this.data = data.concat(buildData(amount))
    },

    createRows( amount) {
      this.numberOfRows = amount;
      this.data = buildData(this.numberOfRows);
    },

    removeRows() {
      this.numberOfRows = 0;
      this.data = [];
    },
  },
}
</script>

// react_test/src/App.js
import React, { Component } from 'react';
import './App.css';
import Menu from './components/Menu';
import Row from './components/Row';
import buildData from './dummyData';

class App extends Component {

  state = {
    data:[],
  }

  create = (amount) => {
    this.setState({ data: buildData(amount) });
    console.log('called')
  }

  add = (amount) => {
    this.setState({ data: this.state.data.concat(buildData(amount)) });
  }

  remove = () => {
    this.setState({ data: [] });
  }


  render() {
    return (
      <div className="App">
        <Menu
          create={this.create}
          add={this.add}
          remove={this.remove}
        />

        <table className="data-table"><tbody>
          {this.state.data.map((item, i) => (
            <Row key={i} item={item} ></Row>
          ))}
        </tbody></table>

      </div>
    );
  }
}

export default App;
